servers:

  operation-servers:
    own-oam:
      basic:
        - service-name: /v1/register-yourself
          uuid: alt-1-0-0-op-s-0000
        - service-name: /v1/embed-yourself
          uuid: alt-1-0-0-op-s-0001
        - service-name: /v1/redirect-service-request-information
          uuid: alt-1-0-0-op-s-0002
        - service-name: /v1/redirect-oam-request-information
          uuid: alt-1-0-0-op-s-0003
        - service-name: /v1/end-subscription
          uuid: alt-1-0-0-op-s-0004
        - service-name: /v1/inquire-oam-request-approvals
          uuid: alt-1-0-0-op-s-0005
        - service-name: /v1/update-client
          uuid: alt-1-0-0-op-s-0007
        - service-name: /v1/list-ltps-and-fcs
          uuid: alt-1-0-0-op-s-0008
        - service-name: /v1/redirect-topology-change-information
          uuid: alt-1-0-0-op-s-0009
        - service-name: /v1/update-operation-key
          uuid: alt-1-0-0-op-s-0010
        - service-name: /v1/update-operation-client
          uuid: alt-1-0-0-op-s-0011
      individual:
        - service-name: /v1/bequeath-your-data-and-die
          uuid: alt-1-0-0-op-s-1000
    service:
      basic:
        - service-name: /v1/start-application-in-generic-representation
          uuid: alt-1-0-0-op-s-2000
        - service-name: /v1/inform-about-application
          uuid: alt-1-0-0-op-s-2001
        - service-name: /v1/inform-about-application-in-generic-representation
          uuid: alt-1-0-0-op-s-2002
        - service-name: /v1/inform-about-release-history
          uuid: alt-1-0-0-op-s-2003
        - service-name: /v1/inform-about-release-history-in-generic-representation
          uuid: alt-1-0-0-op-s-2004
      individual:
        - service-name: /v1/regard-application
          uuid: alt-1-0-0-op-s-3001
        - service-name: /v1/disregard-application
          uuid: alt-1-0-0-op-s-3002
        - service-name: /v1/list-applications
          uuid: alt-1-0-0-op-s-3003
        - service-name: /v1/update-all-ltps-and-fcs
          uuid: alt-1-0-0-op-s-3004
        - service-name: /v1/update-ltp
          uuid: alt-1-0-0-op-s-3005
        - service-name: /v1/delete-ltp-and-dependents
          uuid: alt-1-0-0-op-s-3006
        - service-name: /v1/list-operation-servers-at-application
          uuid: alt-1-0-0-op-s-3009
        - service-name: /v1/list-operation-clients-at-application
          uuid: alt-1-0-0-op-s-3010
        - service-name: /v1/update-fc
          uuid: alt-1-0-0-op-s-3013
        - service-name: /v1/update-fc-port
          uuid: alt-1-0-0-op-s-3014
        - service-name: /v1/delete-fc-port
          uuid: alt-1-0-0-op-s-3015
        - service-name: /v1/list-operation-clients-reacting-on-operation-server
          uuid: alt-1-0-0-op-s-3016
        - service-name: /v1/list-link-uuids
          uuid: alt-1-0-0-op-s-3017
        - service-name: /v1/add-operation-client-to-link
          uuid: alt-1-0-0-op-s-3018
        - service-name: /v1/remove-operation-client-from-link
          uuid: alt-1-0-0-op-s-3019
        - service-name: /v1/list-end-points-of-link
          uuid: alt-1-0-0-op-s-3020
        - service-name: /v1/list-links-to-operation-clients-of-application
          uuid: alt-1-0-0-op-s-3021
        - service-name: /v1/notify-link-updates
          uuid: alt-1-0-0-op-s-3022
  http-server:
    own-application-name: ApplicationLayerTopology
    own-release-number: 1.0.0
    uuid: alt-1-0-0-http-s-0000
  tpc-server:
    - description: Without TLS layer
      local-protocol: http
      own-ip-address: 1.1.3.13
      own-tcp-port: 3013
      uuid: alt-1-0-0-tcp-s-0000
    - description: With TLS layer
      local-protocol: https
      own-ip-address: 1.2.3.13
      own-tcp-port: 3213
      uuid: alt-1-0-0-tcp-s-0001


clients:

  - http-client:
      application-name: OldRelease
      release-number: 1.0.0
      uuid: alt-1-0-0-http-c-0000
    tcp-client:
      ip-address: 10.118.125.157
      tcp-port: 1005
      uuid: alt-1-0-0-tcp-c-0000
    operation-clients:
      own-oam:
        basic:
          - service-name: /v1/bequeath-your-data-and-die
            uuid: alt-1-0-0-op-c-0000
        individual:
      service:
        basic:
        individual:

  - http-client:
      application-name: NewRelease
      release-number: 1.0.0
      uuid: alt-1-0-0-http-c-0010
    tcp-client:
      ip-address: 10.118.125.157
      tcp-port: 1005
      uuid: alt-1-0-0-tcp-c-0010
    operation-clients:
      own-oam:
        basic:
        individual:
          - service-name: /v1/regard-application
            uuid: alt-1-0-0-op-c-1010
          - service-name: /v1/update-all-ltps-and-fcs
            uuid: alt-1-0-0-op-c-1011
          - service-name: /v1/add-operation-client-to-link
            uuid: alt-1-0-0-op-c-1012
      service:
        basic:
        individual:

  - http-client:
      application-name: RegistryOffice
      release-number: 1.0.0
      uuid: alt-1-0-0-http-c-0020
    tcp-client:
      ip-address: 10.118.125.157
      tcp-port: 1000
      uuid: alt-1-0-0-tcp-c-0020
    operation-clients:
      own-oam:
        basic:
          - service-name: /v1/register-application
            uuid: alt-1-0-0-op-c-0020
          - service-name: /v1/relay-server-replacement
            uuid: alt-1-0-0-op-c-0021
          - service-name: /v1/deregister-application
            uuid: alt-1-0-0-op-c-0022
          - service-name: /v1/relay-operation-update
            uuid: alt-1-0-0-op-c-0023
        individual:
          - service-name: /v1/notify-approvals
            uuid: alt-1-0-0-op-c-im-ro-1-0-0-000
          - service-name: /v1/notify-withdrawn-approvals
            uuid: alt-1-0-0-op-c-im-ro-1-0-0-001
          - service-name: /v1/end-subscription
            uuid: alt-1-0-0-op-c-im-ro-1-0-0-002
          - service-name: /v1/redirect-topology-change-information
            uuid: alt-1-0-0-op-c-im-ro-1-0-0-004
      service:
        basic:
        individual:
          - service-name: /v1/list-ltps-and-fcs
            uuid: alt-1-0-0-op-c-is-ro-1-0-0-001

  - http-client:
      application-name: TypeApprovalRegister
      release-number: 1.0.0
      uuid: alt-1-0-0-http-c-2030
    tcp-client:
      ip-address: 10.118.125.157
      tcp-port: 1001
      uuid: alt-1-0-0-tcp-c-2030
    operation-clients:
      own-oam:
        basic:
        individual:
          - service-name: /v1/redirect-topology-change-information
            uuid: alt-1-0-0-op-c-im-tar-1-0-0-000
      service:
        basic:
        individual:
          - service-name: /v1/list-ltps-and-fcs
            uuid: alt-1-0-0-op-c-is-tar-1-0-0-001

  - http-client:
      application-name: ExecutionAndTraceLog
      release-number: 1.0.0
      uuid: alt-1-0-0-http-c-0040
    tcp-client:
      ip-address: 10.118.125.157
      tcp-port: 1002
      uuid: alt-1-0-0-tcp-c-0040
    operation-clients:
      own-oam:
        basic:
        individual:
          - service-name: /v1/redirect-topology-change-information
            uuid: alt-1-0-0-op-c-im-eatl-1-0-0-000
      service:
        basic:
          - service-name: /v1/record-service-request
            uuid: alt-1-0-0-op-c-bs-eatl-1-0-0-000
        individual:
          - service-name: /v1/list-ltps-and-fcs
            uuid: alt-1-0-0-op-c-is-eatl-1-0-0-001

  - http-client:
      application-name: OamLog
      release-number: 1.0.0
      uuid: alt-1-0-0-http-c-0050
    tcp-client:
      ip-address: 10.118.125.157
      tcp-port: 1003
      uuid: alt-1-0-0-tcp-c-0050
    operation-clients:
      own-oam:
        basic:
        individual:
          - service-name: /v1/redirect-topology-change-information
            uuid: alt-1-0-0-op-c-im-ol-1-0-0-000
      service:
        basic:
          - service-name: /v1/record-oam-request
            uuid: alt-1-0-0-op-c-bs-ol-1-0-0-000
        individual:
          - service-name: /v1/list-ltps-and-fcs
            uuid: alt-1-0-0-op-c-is-ol-1-0-0-001

  - http-client:
      application-name: AdministratorAdministration
      release-number: 1.0.0
      uuid: alt-1-0-0-http-c-0060
    tcp-client:
      ip-address: 10.118.125.157
      tcp-port: 1004
      uuid: alt-1-0-0-tcp-c-0060
    operation-clients:
      own-oam:
        basic:
        individual:
          - service-name: /v1/redirect-topology-change-information
            uuid: alt-1-0-0-op-c-im-aa-1-0-0-000
      service:
        basic:
          - service-name: /v1/approve-oam-request
            uuid: alt-1-0-0-op-c-bs-aa-1-0-0-000
        individual:
          - service-name: /v1/list-ltps-and-fcs
            uuid: alt-1-0-0-op-c-is-aa-1-0-0-001

  - http-client:
      application-name: ApplicationLayerTopology
      release-number: 1.0.0
      uuid: alt-1-0-0-http-c-0070
    tcp-client:
      ip-address: 10.118.125.157
      tcp-port: 1005
      uuid: alt-1-0-0-tcp-c-0070
    operation-clients:
      own-oam:
        basic:
          - service-name: /v1/update-all-ltps-and-fcs
            uuid: alt-1-0-0-op-c-0070
          - service-name: /v1/update-ltp
            uuid: alt-1-0-0-op-c-0071
          - service-name: /v1/delete-ltp-and-dependents
            uuid: alt-1-0-0-op-c-0072
          - service-name: /v1/update-fc
            uuid: alt-1-0-0-op-c-0073
          - service-name: /v1/update-fc-port
            uuid: alt-1-0-0-op-c-0074
          - service-name: /v1/delete-fc-port
            uuid: alt-1-0-0-op-c-0075
        individual:
          - service-name: /v1/redirect-topology-change-information
            uuid: alt-1-0-0-op-c-im-alt-1-0-0-000
      service:
        basic:
        individual:
          - service-name: /v1/list-ltps-and-fcs
            uuid: alt-1-0-0-op-c-is-alt-1-0-0-001

  - http-client:
      application-name: OperationKeyManagement
      release-number: 1.0.0
      uuid: alt-1-0-0-http-c-2080
    tcp-client:
      ip-address: 10.118.125.157
      tcp-port: 1006
      uuid: alt-1-0-0-tcp-c-2080
    operation-clients:
      own-oam:
        basic:
        individual:
          - service-name: /v1/redirect-topology-change-information
            uuid: alt-1-0-0-op-c-im-okm-1-0-0-000
      service:
        basic:
        individual:
          - service-name: /v1/regard-updated-link
            uuid: alt-1-0-0-op-c-3080
          - service-name: /v1/list-ltps-and-fcs
            uuid: alt-1-0-0-op-c-is-okm-1-0-0-001

  - http-client:
      application-name: CurrentController
      release-number: 1.0.0
      uuid: alt-1-0-0-http-c-2300
    tcp-client:
      ip-address: 10.118.125.186
      tcp-port: 2000
      uuid: alt-1-0-0-tcp-c-2300
    operation-clients:
      own-oam:
        basic:
        individual:
          - service-name: /v1/redirect-topology-change-information
            uuid: alt-1-0-0-op-c-im-cc-1-0-0-000
      service:
        basic:
        individual:
          - service-name: /v1/list-ltps-and-fcs
            uuid: alt-1-0-0-op-c-is-cc-1-0-0-001